// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.poznan.igr.domain;

import org.springframework.beans.factory.annotation.Configurable;
import pl.poznan.igr.domain.BlobFile;

privileged aspect BlobFile_Roo_Configurable {
    
    declare @type: BlobFile: @Configurable;
    
}
