// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.poznan.igr.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.poznan.igr.domain.Context;
import pl.poznan.igr.domain.ContextDataOnDemand;
import pl.poznan.igr.domain.ContextIntegrationTest;

privileged aspect ContextIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContextIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContextIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContextIntegrationTest: @Transactional;
    
    @Autowired
    ContextDataOnDemand ContextIntegrationTest.dod;
    
    @Test
    public void ContextIntegrationTest.testCountContexts() {
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", dod.getRandomContext());
        long count = Context.countContexts();
        Assert.assertTrue("Counter for 'Context' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContextIntegrationTest.testFindContext() {
        Context obj = dod.getRandomContext();
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Context' failed to provide an identifier", id);
        obj = Context.findContext(id);
        Assert.assertNotNull("Find method for 'Context' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Context' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContextIntegrationTest.testFindAllContexts() {
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", dod.getRandomContext());
        long count = Context.countContexts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Context', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Context> result = Context.findAllContexts();
        Assert.assertNotNull("Find all method for 'Context' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Context' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContextIntegrationTest.testFindContextEntries() {
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", dod.getRandomContext());
        long count = Context.countContexts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Context> result = Context.findContextEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Context' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Context' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContextIntegrationTest.testFlush() {
        Context obj = dod.getRandomContext();
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Context' failed to provide an identifier", id);
        obj = Context.findContext(id);
        Assert.assertNotNull("Find method for 'Context' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContext(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Context' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContextIntegrationTest.testMergeUpdate() {
        Context obj = dod.getRandomContext();
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Context' failed to provide an identifier", id);
        obj = Context.findContext(id);
        boolean modified =  dod.modifyContext(obj);
        Integer currentVersion = obj.getVersion();
        Context merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Context' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContextIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", dod.getRandomContext());
        Context obj = dod.getNewTransientContext(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Context' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Context' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Context' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContextIntegrationTest.testRemove() {
        Context obj = dod.getRandomContext();
        Assert.assertNotNull("Data on demand for 'Context' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Context' failed to provide an identifier", id);
        obj = Context.findContext(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Context' with identifier '" + id + "'", Context.findContext(id));
    }
    
}
