// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.poznan.igr.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pl.poznan.igr.domain.BlobFileDataOnDemand;
import pl.poznan.igr.domain.Context;
import pl.poznan.igr.domain.ContextDataOnDemand;
import pl.poznan.igr.domain.StatsSession;
import pl.poznan.igr.domain.StatsSessionDataOnDemand;

privileged aspect StatsSessionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StatsSessionDataOnDemand: @Component;
    
    private Random StatsSessionDataOnDemand.rnd = new SecureRandom();
    
    private List<StatsSession> StatsSessionDataOnDemand.data;
    
    @Autowired
    BlobFileDataOnDemand StatsSessionDataOnDemand.blobFileDataOnDemand;
    
    @Autowired
    ContextDataOnDemand StatsSessionDataOnDemand.contextDataOnDemand;
    
    public StatsSession StatsSessionDataOnDemand.getNewTransientStatsSession(int index) {
        StatsSession obj = new StatsSession();
        setContext(obj, index);
        setCreationDate(obj, index);
        return obj;
    }
    
    public void StatsSessionDataOnDemand.setContext(StatsSession obj, int index) {
        Context context = contextDataOnDemand.getSpecificContext(index);
        obj.setContext(context);
    }
    
    public void StatsSessionDataOnDemand.setCreationDate(StatsSession obj, int index) {
        Date creationDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationDate(creationDate);
    }
    
    public StatsSession StatsSessionDataOnDemand.getSpecificStatsSession(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StatsSession obj = data.get(index);
        Long id = obj.getId();
        return StatsSession.findStatsSession(id);
    }
    
    public StatsSession StatsSessionDataOnDemand.getRandomStatsSession() {
        init();
        StatsSession obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return StatsSession.findStatsSession(id);
    }
    
    public boolean StatsSessionDataOnDemand.modifyStatsSession(StatsSession obj) {
        return false;
    }
    
    public void StatsSessionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StatsSession.findStatsSessionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StatsSession' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StatsSession>();
        for (int i = 0; i < 10; i++) {
            StatsSession obj = getNewTransientStatsSession(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
