package pl.poznan.igr.domain.type;

public enum Status {

	NEW, UPLOADED, UPLOAD_FAILED, UNZIPPED, UNZIP_FAILED, ANALYSED, ANALYSIS_FAILED, ANALYSIS_SAVED, REZIPPED, FINISHED, FINISHED_WITH_ERRORS, REZIP_FAILED
}
