package pl.poznan.igr.domain.type;

public enum Status {

    NEW, UPLOADED, UPLOAD_FAILED, READY_FOR_ANALYSIS,
    UNZIP_FAILED, ANALYSED, ANALYSIS_FAILED,
    ANALYSIS_SAVED, REZIPPED, FINISHED,
    FINISHED_WITH_ERRORS, REZIP_FAILED
}
