// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.poznan.igr.service;

import org.springframework.beans.factory.annotation.Configurable;
import pl.poznan.igr.service.UnzipServiceIntegration;

privileged aspect UnzipServiceIntegration_Roo_Configurable {
    
    declare @type: UnzipServiceIntegration: @Configurable;
    
}
